import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sphere_view/src/utils/spherical_conventions.dart';
import 'package:sphere_view/src/viewer/sphere_viewer_widget.dart';
import 'package:sphere_view/src/viewer/viewer_controller.dart';

/// Phase 11 §3.3 — the viewer must use the **exact** mapping of Math §3.
///
/// This is the most consequential test in the phase and the reason is the
/// failure mode, not the formula. A sign flip in the viewer produces a
/// *mirrored* view, and a mirrored panorama of a building interior looks
/// entirely plausible: rooms are roughly symmetric, text is rarely legible at
/// viewing zoom, and nobody notices until they try to walk to something. Every
/// visual review of the stitcher's output anyone had ever done would have been
/// performed through it, so the stitcher would be judged — favourably or
/// otherwise — on a lie.
///
/// The technique is Phase 02 §4's, applied to the viewer: render a synthetic
/// equirect containing markers at known yaw/pitch, point the camera at six
/// orientations, and assert each marker lands where the formula says. The
/// expected positions come from [screenPositionOf], which inverts the shader's
/// own transform — so the assertion is between what the GPU actually drew and
/// where the mapping says it should be, not between two copies of one formula.
void main() {
  late ui.FragmentProgram program;

  setUpAll(() async {
    TestWidgetsFlutterBinding.ensureInitialized();
    program = await loadEquirectFragmentProgram();
  });

  /// Direction markers, each a distinct solid colour at a known direction.
  ///
  /// Cardinal points on the horizon plus both poles: six directions that no
  /// symmetry maps onto each other, which is what makes a mirror detectable.
  /// A left/right flip exchanges east and west and leaves everything else
  /// alone — so a test with only north and the zenith would pass through it.
  const markers = <String, ({double yaw, double pitch, int colour})>{
    // yaw 0 is the image centre and the session-start heading (Math §3).
    'N': (yaw: 0.0, pitch: 0.0, colour: 0xFFFF0000),
    // Yaw decreases turning right, so −π/2 is a quarter turn to the right.
    'E': (yaw: -math.pi / 2, pitch: 0.0, colour: 0xFF00FF00),
    'S': (yaw: math.pi, pitch: 0.0, colour: 0xFF0000FF),
    'W': (yaw: math.pi / 2, pitch: 0.0, colour: 0xFFFFFF00),
    'zenith': (yaw: 0.0, pitch: math.pi / 2 - 0.08, colour: 0xFF00FFFF),
    'nadir': (yaw: 0.0, pitch: -math.pi / 2 + 0.08, colour: 0xFFFF00FF),
  };

  const panoWidth = 1024;
  const panoHeight = 512;
  const markerRadiusPx = 26;

  /// Builds the equirect, painting each marker as a disc at the pixel Math §3
  /// puts it at.
  ///
  /// The placement uses [SphericalConventions] — the package's single
  /// implementation of the mapping — so the image is generated by the
  /// convention the stitcher writes with and read back by the viewer's shader.
  /// That is the round trip that matters: it is the same one a real panorama
  /// makes.
  Future<ui.Image> buildMarkerPanorama() async {
    final pixels = Uint32List(panoWidth * panoHeight);
    // Mid-grey background: distinguishable from every marker, and from the
    // black a failed texture upload produces.
    pixels.fillRange(0, pixels.length, 0xFF808080);

    for (final marker in markers.values) {
      final cx = SphericalConventions.xForYaw(marker.yaw, panoWidth.toDouble());
      final cy = SphericalConventions.yForPitch(
        marker.pitch,
        panoHeight.toDouble(),
      );
      for (var dy = -markerRadiusPx; dy <= markerRadiusPx; dy++) {
        for (var dx = -markerRadiusPx; dx <= markerRadiusPx; dx++) {
          if (dx * dx + dy * dy > markerRadiusPx * markerRadiusPx) continue;
          final y = (cy + dy).round();
          if (y < 0 || y >= panoHeight) continue;
          // Wraps horizontally, because x = 0 and x = W are the same meridian
          // (Math §3) and the 'S' marker sits exactly on it.
          final x = ((cx + dx).round() % panoWidth + panoWidth) % panoWidth;
          pixels[y * panoWidth + x] = marker.colour;
        }
      }
    }

    // The buffer is ABGR in memory for `rgba8888`; the colours above are ARGB,
    // so swap the red and blue bytes rather than writing the constants
    // pre-swapped, where a mistake would be invisible.
    final bytes = Uint8List(pixels.length * 4);
    final view = ByteData.sublistView(bytes);
    for (var i = 0; i < pixels.length; i++) {
      final argb = pixels[i];
      final a = (argb >> 24) & 0xFF;
      final r = (argb >> 16) & 0xFF;
      final g = (argb >> 8) & 0xFF;
      final b = argb & 0xFF;
      view.setUint32(i * 4, (a << 24) | (b << 16) | (g << 8) | r, Endian.little);
    }

    final descriptor = ui.ImageDescriptor.raw(
      await ui.ImmutableBuffer.fromUint8List(bytes),
      width: panoWidth,
      height: panoHeight,
      pixelFormat: ui.PixelFormat.rgba8888,
    );
    final codec = await descriptor.instantiateCodec();
    return (await codec.getNextFrame()).image;
  }

  const viewSize = Size(320, 240);

  /// Renders the viewer's own painter and returns the pixels.
  Future<ByteData> render(
    ui.Image panorama,
    SphereViewerController controller,
  ) async {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    SpherePainter(
      program: program,
      panorama: panorama,
      controller: controller,
    ).paint(canvas, viewSize);
    final picture = recorder.endRecording();
    final image = await picture.toImage(
      viewSize.width.toInt(),
      viewSize.height.toInt(),
    );
    final data = await image.toByteData();
    image.dispose();
    picture.dispose();
    return data!;
  }

  int colourAt(ByteData pixels, int x, int y) {
    final offset = (y * viewSize.width.toInt() + x) * 4;
    final r = pixels.getUint8(offset);
    final g = pixels.getUint8(offset + 1);
    final b = pixels.getUint8(offset + 2);
    final a = pixels.getUint8(offset + 3);
    return (a << 24) | (r << 16) | (g << 8) | b;
  }

  /// The six camera orientations §3.4 asks for.
  ///
  /// Chosen so that between them every marker is on screen at least once, and
  /// so that yaw, pitch and roll are each non-zero somewhere — a mapping can be
  /// right at the identity and wrong the moment the camera turns, which is the
  /// case a single centred render would miss.
  const orientations = <String, ({double yaw, double pitch, double roll})>{
    'level, facing the session-start heading': (yaw: 0, pitch: 0, roll: 0),
    'a quarter turn right': (yaw: -math.pi / 2, pitch: 0, roll: 0),
    'a quarter turn left': (yaw: math.pi / 2, pitch: 0, roll: 0),
    'turned all the way round': (yaw: math.pi, pitch: 0, roll: 0),
    'looking up': (yaw: 0, pitch: 1.2, roll: 0),
    'looking down and rolled': (yaw: 0.6, pitch: -1.1, roll: 0.35),
  };

  group('direction markers land where Math §3 says', () {
    late ui.Image panorama;

    setUpAll(() async => panorama = await buildMarkerPanorama());
    tearDownAll(() => panorama.dispose());

    for (final entry in orientations.entries) {
      test(entry.key, () async {
        final o = entry.value;
        final controller = SphereViewerController(
          initialYaw: o.yaw,
          initialPitch: o.pitch,
          initialFovDegrees: 90,
        )..roll = o.roll;
        addTearDown(controller.dispose);

        final pixels = await render(panorama, controller);
        var checked = 0;

        for (final marker in markers.entries) {
          final expected = screenPositionOf(
            worldYaw: marker.value.yaw,
            worldPitch: marker.value.pitch,
            cameraYaw: controller.yaw,
            cameraPitch: controller.pitch,
            cameraRoll: controller.roll,
            fov: controller.fov,
            size: viewSize,
          );
          if (expected == null) continue; // off screen at this orientation

          final x = expected.x.round();
          final y = expected.y.round();
          // Skip markers whose predicted centre is within a marker radius of
          // the frame edge: the disc is clipped there and its apparent centre
          // moves, which would make the test assert on the clipping rather
          // than on the mapping.
          if (x < 30 ||
              y < 30 ||
              x >= viewSize.width - 30 ||
              y >= viewSize.height - 30) {
            continue;
          }

          expect(
            colourAt(pixels, x, y),
            marker.value.colour,
            reason:
                'marker ${marker.key} (yaw ${marker.value.yaw.toStringAsFixed(2)}, '
                'pitch ${marker.value.pitch.toStringAsFixed(2)}) should be at '
                '($x, $y) with the camera "${entry.key}". A wrong colour here '
                'is a mirrored or rotated view, which looks plausible and '
                'would invalidate every visual review of the stitcher.',
          );
          checked++;
        }

        expect(
          checked,
          greaterThan(0),
          reason: 'no marker was on screen, so this orientation proved nothing',
        );
      });
    }
  });

  group('the mapping is not mirrored', () {
    late ui.Image panorama;

    setUpAll(() async => panorama = await buildMarkerPanorama());
    tearDownAll(() => panorama.dispose());

    test('east is to the right of north', () async {
      // The single check a horizontal flip cannot survive, stated as a fact
      // about the world rather than about a formula: turning right takes you
      // towards east, so east is the marker on the right-hand side.
      //
      // Viewed from halfway between the two. North and east are a quarter turn
      // apart, and the widest field this viewer allows spans ~116° across a
      // 4:3 frame — enough to hold both only if the camera sits between them,
      // which is also where their left/right relationship is least ambiguous.
      final controller = SphereViewerController(
        initialYaw: -math.pi / 4,
        initialFovDegrees: 100,
      );
      addTearDown(controller.dispose);
      final pixels = await render(panorama, controller);

      final middleRow = viewSize.height ~/ 2;

      /// The centre column of a marker, as the midpoint of its extent.
      ///
      /// Not the first matching pixel: a disc is tens of pixels across at this
      /// zoom, so the leading edge sits a marker-radius left of where the
      /// marker actually is, and a test written against it would be asserting
      /// on the disc's size.
      double? findColumn(int colour) {
        var first = -1;
        var last = -1;
        for (var x = 0; x < viewSize.width; x++) {
          if (colourAt(pixels, x, middleRow) == colour) {
            if (first < 0) first = x;
            last = x;
          }
        }
        return first < 0 ? null : (first + last) / 2;
      }

      final north = findColumn(0xFFFF0000);
      final east = findColumn(0xFF00FF00);
      final west = findColumn(0xFFFFFF00);

      expect(north, isNotNull, reason: 'north should be in the left half');
      expect(east, isNotNull, reason: 'east should be in the right half');
      expect(
        east!,
        greaterThan(north!),
        reason: 'east is to the right of north; if it is to the left the view '
            'is mirrored, which looks entirely plausible and would invalidate '
            'every visual review of the stitcher',
      );
      expect(
        north,
        lessThan(viewSize.width / 2),
        reason: 'with the camera halfway between them, north is left of centre',
      );
      expect(east, greaterThan(viewSize.width / 2));
      expect(
        west,
        isNull,
        reason: 'west is behind the camera here and must not be drawn; if it '
            'appears, yaw is running backwards',
      );
    });

    test('the zenith is up and the nadir is down', () async {
      // The vertical counterpart. A flipped v puts the ceiling underfoot,
      // which — unlike the horizontal flip — people do notice, but only after
      // they have already trusted the image for something.
      //
      // The camera has to be pitched to see a pole at all: the markers sit at
      // ±85°, and a 100° *vertical* field reaches only ±50° from wherever it
      // points. So each pole is checked from a camera tilted halfway towards
      // it, which is also the stronger test — if the pitch sign were inverted,
      // tilting up would bring the *nadir* into view.
      final middleColumn = viewSize.width ~/ 2;

      double? findRow(ByteData pixels, int colour) {
        var first = -1;
        var last = -1;
        for (var y = 0; y < viewSize.height; y++) {
          if (colourAt(pixels, middleColumn, y) == colour) {
            if (first < 0) first = y;
            last = y;
          }
        }
        return first < 0 ? null : (first + last) / 2;
      }

      final lookingUp = SphereViewerController(
        initialPitch: 0.95,
        initialFovDegrees: 100,
      );
      addTearDown(lookingUp.dispose);
      final zenith = findRow(await render(panorama, lookingUp), 0xFF00FFFF);
      expect(
        zenith,
        isNotNull,
        reason: 'tilting up towards the zenith should bring the zenith marker '
            'into view; if it does not, pitch is inverted',
      );
      // Screen y increases downwards, so "above centre" is a smaller y.
      expect(zenith!, lessThan(viewSize.height / 2));

      final lookingDown = SphereViewerController(
        initialPitch: -0.95,
        initialFovDegrees: 100,
      );
      addTearDown(lookingDown.dispose);
      final nadir = findRow(await render(panorama, lookingDown), 0xFFFF00FF);
      expect(nadir, isNotNull);
      expect(nadir!, greaterThan(viewSize.height / 2));
    });

    test('looking up moves the ceiling to the centre', () async {
      // Pitch sign, stated behaviourally. Positive pitch looks up, so the
      // zenith marker moves towards the middle of the screen rather than away.
      final level = SphereViewerController(initialFovDegrees: 90);
      final raised = SphereViewerController(
        initialPitch: math.pi / 2 - 0.08,
        initialFovDegrees: 90,
      );
      addTearDown(level.dispose);
      addTearDown(raised.dispose);

      final pixels = await render(panorama, raised);
      expect(
        colourAt(pixels, viewSize.width ~/ 2, viewSize.height ~/ 2),
        0xFF00FFFF,
        reason: 'pitching up to the zenith should put the zenith marker dead '
            'centre; anything else is an inverted pitch',
      );
    });
  });
}
