// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Which way a physical camera points.
enum PlatformCameraFacing {
  back,
  front,
  external,
}

/// The device thermal state, normalised across the two platforms'
/// differently-grained scales.
enum PlatformThermalState {
  nominal,
  fair,
  serious,
  critical,
}

/// How much of the AE/AWB/AF lock the platform actually granted.
enum PlatformLockQuality {
  fullyLocked,
  bestEffort,
  unlocked,
}

/// Which clock a frame timestamp is expressed on *before* the plugin converts
/// it (§2.5, §3.5). Recorded rather than assumed, because the conversion is
/// different for each and getting it wrong is a silent 10–50 ms pose error.
enum PlatformTimestampBase {
  /// Android `SENSOR_INFO_TIMESTAMP_SOURCE == REALTIME`:
  /// `SystemClock.elapsedRealtimeNanos()`, the same base as
  /// `SensorEvent.timestamp`. Directly comparable, offset exactly zero.
  androidRealtime,
  /// Android `SENSOR_INFO_TIMESTAMP_SOURCE == UNKNOWN`: `System.nanoTime()`,
  /// which is *not* the sensor base. An offset must be estimated.
  androidMonotonicUnknown,
  /// iOS `CMClockGetHostTimeClock` (`mach_absolute_time`). `CMDeviceMotion`
  /// reports `systemUptime`; the plugin measures the offset rather than
  /// assuming the two are identical.
  iosHostTime,
}

/// What the burst actually asks the sensor for.
enum PlatformCaptureFormat {
  /// Direct JPEG burst. The straightforward path.
  jpeg,
  /// `YUV_420_888` burst with the JPEG encode deferred off the capture
  /// thread. R3 §9 found evidence (Nexus 5: ~243 ms JPEG stall vs ~0 ms YUV)
  /// that encoding, not sensor readout, dominates per-frame latency — so this
  /// is the cheapest way to recover a burst that misses the 600 ms budget,
  /// far cheaper than abandoning HDR. Android only.
  yuvDeferredJpeg,
}

/// How the bracket was actually produced, so a degraded path is recorded
/// rather than mistaken for the real thing (architecture §8).
enum PlatformBracketMode {
  /// The intended path: explicit per-request exposure time with AE off.
  manualExposureBurst,
  /// No `MANUAL_SENSOR`: `CONTROL_AE_EXPOSURE_COMPENSATION` per request. Not a
  /// true bracket — AE is still deciding — and it must not be read as one.
  aeCompensationBurst,
  /// iOS `AVCapturePhotoBracketSettings` with manual exposure settings.
  photoBracket,
  /// `maxBracketedCapturePhotoCount` came back below the requested count:
  /// sequential single shots with the exposure changed between them. Slower,
  /// and the frames are further apart in time.
  sequentialManual,
  /// No usable exposure control at all. One frame at the metered lock.
  singleShot,
}

/// Android `INFO_SUPPORTED_HARDWARE_LEVEL`. Recorded but **not** gated on —
/// R3 §8 is explicit that the gate is `MANUAL_SENSOR` in
/// `REQUEST_AVAILABLE_CAPABILITIES`, because `LIMITED` devices may or may not
/// have it. Both are reported so the findings can show whether the two ever
/// disagree on real fleet hardware.
enum PlatformHardwareLevel {
  legacy,
  limited,
  full,
  level3,
  external,
  unknown,
}

/// Which reference frame a platform attitude quaternion is expressed against.
///
/// Carried on every sample rather than inferred from `Platform.isAndroid`,
/// because it is the input to the one conversion Phase 07 §2 explicitly says
/// **must not be trusted to derivation** — the doc's own Android derivation
/// produces a determinant −1 matrix, which would mirror the panorama. Naming
/// the source frame in the data is what lets `pose_frame_conversion.dart` hold
/// one tested conversion per frame instead of one per platform guess.
enum PlatformPoseFrame {
  /// Android `TYPE_GAME_ROTATION_VECTOR`: device→world, where the world frame
  /// is `X` ≈ east, `Y` ≈ north, **`Z` up**. Gyro + accelerometer, bias- and
  /// scale-corrected by the OS filter, and — the reason it is used instead of
  /// `TYPE_ROTATION_VECTOR` — **no magnetometer**, so rebar, lift motors and
  /// steel studs cannot bend the heading (Phase 07 §1, Math §1.1).
  androidGameRotationVector,
  /// iOS `CMDeviceMotion.attitude.quaternion` under
  /// `.xArbitraryCorrectedZVertical`: device→reference, reference `Z`
  /// vertical, `X` an arbitrary horizontal direction, yaw drift-corrected.
  /// Chosen over `.xTrueNorthZVertical` for the same magnetometer reason.
  iosXArbitraryCorrectedZVertical,
}

/// Which clock a pose sample's timestamp is on, before any conversion.
///
/// Separate from [PlatformTimestampBase], which describes the *camera*. Phase
/// 07 §6 pitfall 1 is that `SensorEvent.timestamp`'s base "varies by device" —
/// usually `elapsedRealtimeNanos`, but not universally — and Phase 06's
/// `TimestampMapper` already assumed the usual case when it put camera frames
/// on `elapsedRealtimeNanos` and called the offset exactly zero. That
/// assumption is now *measured* on the pose side rather than inherited, because
/// if it is wrong the two clocks silently disagree by however long the device
/// has been asleep.
enum PlatformPoseClockBase {
  /// `SensorEvent.timestamp` is `SystemClock.elapsedRealtimeNanos()`. The
  /// documented and near-universal case, and the one Phase 06's camera-side
  /// `REALTIME` mapping pairs with exactly.
  androidElapsedRealtime,
  /// `SensorEvent.timestamp` is `System.nanoTime()` — the device that pitfall 1
  /// warns about. The offset is real, device-specific, and measured.
  androidMonotonicNanoTime,
  /// `CMDeviceMotion.timestamp`, seconds since boot on `systemUptime` — the
  /// same base Phase 06's iOS `TimestampMapper` converts sample buffers onto.
  iosSystemUptime,
}

/// Pixel dimensions. Not `dart:ui.Size` — see `ImageSize`, which this maps to.
class PlatformSize {
  PlatformSize({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformSize decode(Object result) {
    result as List<Object?>;
    return PlatformSize(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSize(width: $width, height: $height)';
  }
}

/// A rectangle in sensor-array coordinates, `[left, top, width, height]`.
class PlatformRect {
  PlatformRect({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  int left;

  int top;

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[
      left,
      top,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformRect decode(Object result) {
    result as List<Object?>;
    return PlatformRect(
      left: result[0]! as int,
      top: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) && _deepEquals(top, other.top) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformRect(left: $left, top: $top, width: $width, height: $height)';
  }
}

/// One physical camera, with enough capability detail for Dart to choose.
class CameraDescriptor {
  CameraDescriptor({
    required this.id,
    required this.facing,
    required this.availableSizes,
    required this.focalLengthsMm,
    required this.supportsBracketing,
    required this.maxBracketCount,
    required this.hasDistortionModel,
    required this.hardwareLevel,
    required this.hasManualSensor,
    required this.isLogicalMultiCamera,
    this.excludedReason,
  });

  String id;

  PlatformCameraFacing facing;

  /// Still-capture sizes offered, largest first.
  List<PlatformSize> availableSizes;

  /// `LENS_INFO_AVAILABLE_FOCAL_LENGTHS` on Android; the single lens focal on
  /// iOS where derivable. Used to exclude the ultra-wide: §2.1 picks the
  /// camera whose focal is *not* the shortest.
  List<double> focalLengthsMm;

  /// Whether a real per-frame-controlled bracket is available.
  bool supportsBracketing;

  /// iOS `maxBracketedCapturePhotoCount`, queried at runtime after the format
  /// is set — R3 §4: it is not a fixed number and has no published per-device
  /// table. On Android this is the burst length the session will accept.
  int maxBracketCount;

  /// Whether a lens distortion model can be obtained. Frequently false: R2
  /// found `LENS_DISTORTION` null even on Pixel hardware, and iOS only has a
  /// LUT on devices that deliver calibration data at all.
  bool hasDistortionModel;

  PlatformHardwareLevel hardwareLevel;

  /// `MANUAL_SENSOR` in `REQUEST_AVAILABLE_CAPABILITIES`. **This** is the
  /// gate, not [hardwareLevel] (R3 §8).
  bool hasManualSensor;

  bool isLogicalMultiCamera;

  /// Why selection skipped this camera, when it did. §2.1 asks for the
  /// ultra-wide to be excluded *and logged*, since a future config may want it.
  String? excludedReason;

  List<Object?> _toList() {
    return <Object?>[
      id,
      facing,
      availableSizes,
      focalLengthsMm,
      supportsBracketing,
      maxBracketCount,
      hasDistortionModel,
      hardwareLevel,
      hasManualSensor,
      isLogicalMultiCamera,
      excludedReason,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraDescriptor decode(Object result) {
    result as List<Object?>;
    return CameraDescriptor(
      id: result[0]! as String,
      facing: result[1]! as PlatformCameraFacing,
      availableSizes: (result[2]! as List<Object?>).cast<PlatformSize>(),
      focalLengthsMm: (result[3]! as List<Object?>).cast<double>(),
      supportsBracketing: result[4]! as bool,
      maxBracketCount: result[5]! as int,
      hasDistortionModel: result[6]! as bool,
      hardwareLevel: result[7]! as PlatformHardwareLevel,
      hasManualSensor: result[8]! as bool,
      isLogicalMultiCamera: result[9]! as bool,
      excludedReason: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraDescriptor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(facing, other.facing) && _deepEquals(availableSizes, other.availableSizes) && _deepEquals(focalLengthsMm, other.focalLengthsMm) && _deepEquals(supportsBracketing, other.supportsBracketing) && _deepEquals(maxBracketCount, other.maxBracketCount) && _deepEquals(hasDistortionModel, other.hasDistortionModel) && _deepEquals(hardwareLevel, other.hardwareLevel) && _deepEquals(hasManualSensor, other.hasManualSensor) && _deepEquals(isLogicalMultiCamera, other.isLogicalMultiCamera) && _deepEquals(excludedReason, other.excludedReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraDescriptor(id: $id, facing: $facing, availableSizes: $availableSizes, focalLengthsMm: $focalLengthsMm, supportsBracketing: $supportsBracketing, maxBracketCount: $maxBracketCount, hasDistortionModel: $hasDistortionModel, hardwareLevel: $hardwareLevel, hasManualSensor: $hasManualSensor, isLogicalMultiCamera: $isLogicalMultiCamera, excludedReason: $excludedReason)';
  }
}

/// What Dart asks the platform to configure.
class CaptureFormatRequest {
  CaptureFormatRequest({
    this.captureSize,
    required this.preferFourThree,
    required this.previewTargetWidth,
    required this.format,
    required this.jpegQuality,
    required this.computeFrameStatistics,
  });

  /// `null` means "pick the largest, subject to [preferFourThree]".
  PlatformSize? captureSize;

  /// Prefer a 4:3 output: it matches the sensor's full active array, so no
  /// crop factor enters the intrinsics (§2.1, Math §4.1), and it gives the
  /// largest vertical FOV, which directly reduces the number of rings.
  bool preferFourThree;

  /// ~1280. Preview is only used for aiming; a full-resolution preview on a
  /// tablet burns battery and thermal headroom the stitch will need (§4).
  int previewTargetWidth;

  PlatformCaptureFormat format;

  int jpegQuality;

  /// Compute a centre-crop mean RGB per delivered frame. Off in production;
  /// on for the grey-card lock test (§6), which needs a *measurement* rather
  /// than an eyeball.
  bool computeFrameStatistics;

  List<Object?> _toList() {
    return <Object?>[
      captureSize,
      preferFourThree,
      previewTargetWidth,
      format,
      jpegQuality,
      computeFrameStatistics,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureFormatRequest decode(Object result) {
    result as List<Object?>;
    return CaptureFormatRequest(
      captureSize: result[0] as PlatformSize?,
      preferFourThree: result[1]! as bool,
      previewTargetWidth: result[2]! as int,
      format: result[3]! as PlatformCaptureFormat,
      jpegQuality: result[4]! as int,
      computeFrameStatistics: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureFormatRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(captureSize, other.captureSize) && _deepEquals(preferFourThree, other.preferFourThree) && _deepEquals(previewTargetWidth, other.previewTargetWidth) && _deepEquals(format, other.format) && _deepEquals(jpegQuality, other.jpegQuality) && _deepEquals(computeFrameStatistics, other.computeFrameStatistics);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureFormatRequest(captureSize: $captureSize, preferFourThree: $preferFourThree, previewTargetWidth: $previewTargetWidth, format: $format, jpegQuality: $jpegQuality, computeFrameStatistics: $computeFrameStatistics)';
  }
}

/// The raw Android facts Math §4.1 derives intrinsics from. Every field is
/// straight out of `CameraCharacteristics` or the configured stream — no
/// arithmetic happens on the Kotlin side.
class AndroidIntrinsicFacts {
  AndroidIntrinsicFacts({
    this.focalLengthMm,
    this.sensorPhysicalWidthMm,
    this.sensorPhysicalHeightMm,
    this.pixelArraySize,
    this.preCorrectionActiveArray,
    this.activeArray,
    this.cropRegion,
    this.lensIntrinsicCalibration,
    this.lensDistortion,
    required this.distortionCorrectionModeOffRequested,
    required this.distortionCorrectionSupportsNonOff,
    required this.activeArraysDiffer,
    this.focalLengthIn35mmFilm,
  });

  /// `LENS_INFO_AVAILABLE_FOCAL_LENGTHS[i]` actually in force.
  double? focalLengthMm;

  /// `SENSOR_INFO_PHYSICAL_SIZE`.
  double? sensorPhysicalWidthMm;

  double? sensorPhysicalHeightMm;

  /// `SENSOR_INFO_PIXEL_ARRAY_SIZE` — the denominator of the pixel pitch.
  PlatformSize? pixelArraySize;

  /// `SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE`. Math §4.1 anchors
  /// *every* coordinate to this frame.
  PlatformRect? preCorrectionActiveArray;

  /// `SENSOR_INFO_ACTIVE_ARRAY_SIZE`, for the [activeArraysDiffer] check.
  PlatformRect? activeArray;

  /// The `SCALER_CROP_REGION` actually applied. Full array when not zoomed.
  PlatformRect? cropRegion;

  /// `LENS_INTRINSIC_CALIBRATION` = `[fx, fy, cx, cy, s]` in
  /// pre-correction-array pixels, or null. R2: gated by no capability flag,
  /// documented "may be null", reported null even on Pixel hardware — so this
  /// is an **override**, not the primary path.
  List<double>? lensIntrinsicCalibration;

  /// `LENS_DISTORTION` = `[κ1, κ2, κ3, κ4, κ5]`, **unreordered**. The reorder
  /// to OpenCV's `(k1, k2, p1, p2, k3)` happens in Dart, in the one place it
  /// already lives.
  List<double>? lensDistortion;

  /// Whether `DISTORTION_CORRECTION_MODE_OFF` was requested on every capture.
  bool distortionCorrectionModeOffRequested;

  /// Whether this device lists any mode other than `OFF`. R2 §4: most do not,
  /// and where none does, the pre-correction/active distinction is moot.
  bool distortionCorrectionSupportsNonOff;

  /// Whether the two array rectangles actually differ on this device.
  bool activeArraysDiffer;

  /// EXIF last resort: `fx = W · FocalLengthIn35mmFilm / 36`.
  double? focalLengthIn35mmFilm;

  List<Object?> _toList() {
    return <Object?>[
      focalLengthMm,
      sensorPhysicalWidthMm,
      sensorPhysicalHeightMm,
      pixelArraySize,
      preCorrectionActiveArray,
      activeArray,
      cropRegion,
      lensIntrinsicCalibration,
      lensDistortion,
      distortionCorrectionModeOffRequested,
      distortionCorrectionSupportsNonOff,
      activeArraysDiffer,
      focalLengthIn35mmFilm,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidIntrinsicFacts decode(Object result) {
    result as List<Object?>;
    return AndroidIntrinsicFacts(
      focalLengthMm: result[0] as double?,
      sensorPhysicalWidthMm: result[1] as double?,
      sensorPhysicalHeightMm: result[2] as double?,
      pixelArraySize: result[3] as PlatformSize?,
      preCorrectionActiveArray: result[4] as PlatformRect?,
      activeArray: result[5] as PlatformRect?,
      cropRegion: result[6] as PlatformRect?,
      lensIntrinsicCalibration: (result[7] as List<Object?>?)?.cast<double>(),
      lensDistortion: (result[8] as List<Object?>?)?.cast<double>(),
      distortionCorrectionModeOffRequested: result[9]! as bool,
      distortionCorrectionSupportsNonOff: result[10]! as bool,
      activeArraysDiffer: result[11]! as bool,
      focalLengthIn35mmFilm: result[12] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidIntrinsicFacts || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(focalLengthMm, other.focalLengthMm) && _deepEquals(sensorPhysicalWidthMm, other.sensorPhysicalWidthMm) && _deepEquals(sensorPhysicalHeightMm, other.sensorPhysicalHeightMm) && _deepEquals(pixelArraySize, other.pixelArraySize) && _deepEquals(preCorrectionActiveArray, other.preCorrectionActiveArray) && _deepEquals(activeArray, other.activeArray) && _deepEquals(cropRegion, other.cropRegion) && _deepEquals(lensIntrinsicCalibration, other.lensIntrinsicCalibration) && _deepEquals(lensDistortion, other.lensDistortion) && _deepEquals(distortionCorrectionModeOffRequested, other.distortionCorrectionModeOffRequested) && _deepEquals(distortionCorrectionSupportsNonOff, other.distortionCorrectionSupportsNonOff) && _deepEquals(activeArraysDiffer, other.activeArraysDiffer) && _deepEquals(focalLengthIn35mmFilm, other.focalLengthIn35mmFilm);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidIntrinsicFacts(focalLengthMm: $focalLengthMm, sensorPhysicalWidthMm: $sensorPhysicalWidthMm, sensorPhysicalHeightMm: $sensorPhysicalHeightMm, pixelArraySize: $pixelArraySize, preCorrectionActiveArray: $preCorrectionActiveArray, activeArray: $activeArray, cropRegion: $cropRegion, lensIntrinsicCalibration: $lensIntrinsicCalibration, lensDistortion: $lensDistortion, distortionCorrectionModeOffRequested: $distortionCorrectionModeOffRequested, distortionCorrectionSupportsNonOff: $distortionCorrectionSupportsNonOff, activeArraysDiffer: $activeArraysDiffer, focalLengthIn35mmFilm: $focalLengthIn35mmFilm)';
  }
}

/// The raw iOS facts Math §4.2 derives intrinsics from, one field per tier of
/// the chain so the resolver can say which rung it reached.
class IosIntrinsicFacts {
  IosIntrinsicFacts({
    this.calibrationIntrinsicMatrix,
    this.calibrationReferenceSize,
    this.connectionIntrinsicMatrix,
    this.connectionIntrinsicReferenceSize,
    required this.connectionIntrinsicDeliverySupported,
    required this.connectionIntrinsicAttachmentArrived,
    required this.videoFieldOfViewDegrees,
    this.lensDistortionLookupTable,
    this.lensDistortionCenterX,
    this.lensDistortionCenterY,
    required this.geometricDistortionCorrectionDisabled,
    required this.contentAwareDistortionCorrectionDisabled,
    required this.calibrationDataDeliverySupported,
    required this.isVirtualDevice,
    this.focalLengthIn35mmFilm,
  });

  /// Tier 1: `AVCameraCalibrationData.intrinsicMatrix`, row-major 3×3, valid
  /// for [calibrationReferenceSize]. R2: needs a multi-camera virtual device,
  /// which excludes base iPad, Air and mini outright — expect null.
  List<double>? calibrationIntrinsicMatrix;

  PlatformSize? calibrationReferenceSize;

  /// Tier 2: `AVCaptureConnection.cameraIntrinsicMatrix`, delivered as a
  /// `CMSampleBuffer` attachment on `AVCaptureVideoDataOutput` — *not* photo
  /// output. The only measured path on a single-lens iPad, and its
  /// availability there is contested (R2 "Still unknown" #1).
  List<double>? connectionIntrinsicMatrix;

  PlatformSize? connectionIntrinsicReferenceSize;

  /// The capability flag says "supported"…
  bool connectionIntrinsicDeliverySupported;

  /// …and this says the attachment *actually arrived on real frames*. The
  /// distinction is the whole point: reporting the flag alone is the mistake
  /// that left this question open since 2017 (Spike B).
  bool connectionIntrinsicAttachmentArrived;

  /// Tier 3, and the realistic primary: `videoFieldOfView`, confirmed by R2 to
  /// be **horizontal**. `fx = (W/2) / tan(FOV/2)`. This is *not*
  /// `geometricDistortionCorrectedVideoFieldOfView`, which describes the
  /// post-GDC frame and only applies while GDC is on.
  double videoFieldOfViewDegrees;

  /// `lensDistortionLookupTable` — radial magnification factors from
  /// [lensDistortionCenterX]/[lensDistortionCenterY] to the farthest corner.
  /// Purely radial: the Brown–Conrady fit forces `p1 = p2 = 0`.
  List<double>? lensDistortionLookupTable;

  double? lensDistortionCenterX;

  double? lensDistortionCenterY;

  /// Mandatory on every capture, whichever tier is used (R2 §8). Reported so
  /// a violation is visible rather than assumed away.
  bool geometricDistortionCorrectionDisabled;

  bool contentAwareDistortionCorrectionDisabled;

  bool calibrationDataDeliverySupported;

  bool isVirtualDevice;

  /// EXIF last resort.
  double? focalLengthIn35mmFilm;

  List<Object?> _toList() {
    return <Object?>[
      calibrationIntrinsicMatrix,
      calibrationReferenceSize,
      connectionIntrinsicMatrix,
      connectionIntrinsicReferenceSize,
      connectionIntrinsicDeliverySupported,
      connectionIntrinsicAttachmentArrived,
      videoFieldOfViewDegrees,
      lensDistortionLookupTable,
      lensDistortionCenterX,
      lensDistortionCenterY,
      geometricDistortionCorrectionDisabled,
      contentAwareDistortionCorrectionDisabled,
      calibrationDataDeliverySupported,
      isVirtualDevice,
      focalLengthIn35mmFilm,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosIntrinsicFacts decode(Object result) {
    result as List<Object?>;
    return IosIntrinsicFacts(
      calibrationIntrinsicMatrix: (result[0] as List<Object?>?)?.cast<double>(),
      calibrationReferenceSize: result[1] as PlatformSize?,
      connectionIntrinsicMatrix: (result[2] as List<Object?>?)?.cast<double>(),
      connectionIntrinsicReferenceSize: result[3] as PlatformSize?,
      connectionIntrinsicDeliverySupported: result[4]! as bool,
      connectionIntrinsicAttachmentArrived: result[5]! as bool,
      videoFieldOfViewDegrees: result[6]! as double,
      lensDistortionLookupTable: (result[7] as List<Object?>?)?.cast<double>(),
      lensDistortionCenterX: result[8] as double?,
      lensDistortionCenterY: result[9] as double?,
      geometricDistortionCorrectionDisabled: result[10]! as bool,
      contentAwareDistortionCorrectionDisabled: result[11]! as bool,
      calibrationDataDeliverySupported: result[12]! as bool,
      isVirtualDevice: result[13]! as bool,
      focalLengthIn35mmFilm: result[14] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosIntrinsicFacts || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(calibrationIntrinsicMatrix, other.calibrationIntrinsicMatrix) && _deepEquals(calibrationReferenceSize, other.calibrationReferenceSize) && _deepEquals(connectionIntrinsicMatrix, other.connectionIntrinsicMatrix) && _deepEquals(connectionIntrinsicReferenceSize, other.connectionIntrinsicReferenceSize) && _deepEquals(connectionIntrinsicDeliverySupported, other.connectionIntrinsicDeliverySupported) && _deepEquals(connectionIntrinsicAttachmentArrived, other.connectionIntrinsicAttachmentArrived) && _deepEquals(videoFieldOfViewDegrees, other.videoFieldOfViewDegrees) && _deepEquals(lensDistortionLookupTable, other.lensDistortionLookupTable) && _deepEquals(lensDistortionCenterX, other.lensDistortionCenterX) && _deepEquals(lensDistortionCenterY, other.lensDistortionCenterY) && _deepEquals(geometricDistortionCorrectionDisabled, other.geometricDistortionCorrectionDisabled) && _deepEquals(contentAwareDistortionCorrectionDisabled, other.contentAwareDistortionCorrectionDisabled) && _deepEquals(calibrationDataDeliverySupported, other.calibrationDataDeliverySupported) && _deepEquals(isVirtualDevice, other.isVirtualDevice) && _deepEquals(focalLengthIn35mmFilm, other.focalLengthIn35mmFilm);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'IosIntrinsicFacts(calibrationIntrinsicMatrix: $calibrationIntrinsicMatrix, calibrationReferenceSize: $calibrationReferenceSize, connectionIntrinsicMatrix: $connectionIntrinsicMatrix, connectionIntrinsicReferenceSize: $connectionIntrinsicReferenceSize, connectionIntrinsicDeliverySupported: $connectionIntrinsicDeliverySupported, connectionIntrinsicAttachmentArrived: $connectionIntrinsicAttachmentArrived, videoFieldOfViewDegrees: $videoFieldOfViewDegrees, lensDistortionLookupTable: $lensDistortionLookupTable, lensDistortionCenterX: $lensDistortionCenterX, lensDistortionCenterY: $lensDistortionCenterY, geometricDistortionCorrectionDisabled: $geometricDistortionCorrectionDisabled, contentAwareDistortionCorrectionDisabled: $contentAwareDistortionCorrectionDisabled, calibrationDataDeliverySupported: $calibrationDataDeliverySupported, isVirtualDevice: $isVirtualDevice, focalLengthIn35mmFilm: $focalLengthIn35mmFilm)';
  }
}

/// How frame timestamps were converted to the one monotonic microsecond base
/// the pose stream also uses (§2.5, §3.5).
///
/// This travels into the bundle. A 10–50 ms mismatch is 0.6–3° of rotation
/// error at a realistic 60°/s pan — larger than everything Phase 03 works to
/// remove, and it presents as a stitcher bug. If it ever goes wrong, this
/// record is how it gets found.
class ClockSyncInfo {
  ClockSyncInfo({
    required this.base,
    required this.offsetUs,
    required this.uncertaintyUs,
    required this.note,
  });

  PlatformTimestampBase base;

  /// Added to the camera's raw timestamp to land on the sensor/motion clock.
  /// Exactly `0` for [PlatformTimestampBase.androidRealtime].
  int offsetUs;

  /// Half the spread of the offset estimator's samples. Zero when the two
  /// clocks are the same clock and no estimation was needed.
  int uncertaintyUs;

  String note;

  List<Object?> _toList() {
    return <Object?>[
      base,
      offsetUs,
      uncertaintyUs,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static ClockSyncInfo decode(Object result) {
    result as List<Object?>;
    return ClockSyncInfo(
      base: result[0]! as PlatformTimestampBase,
      offsetUs: result[1]! as int,
      uncertaintyUs: result[2]! as int,
      note: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ClockSyncInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(base, other.base) && _deepEquals(offsetUs, other.offsetUs) && _deepEquals(uncertaintyUs, other.uncertaintyUs) && _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ClockSyncInfo(base: $base, offsetUs: $offsetUs, uncertaintyUs: $uncertaintyUs, note: $note)';
  }
}

/// One instantaneous re-measurement of the two clocks, for the §6 stability
/// test ("offset stable within ±2 ms over 60 s").
class ClockOffsetSample {
  ClockOffsetSample({
    required this.cameraClockUs,
    required this.motionClockUs,
    required this.offsetUs,
    required this.uncertaintyUs,
  });

  int cameraClockUs;

  int motionClockUs;

  int offsetUs;

  int uncertaintyUs;

  List<Object?> _toList() {
    return <Object?>[
      cameraClockUs,
      motionClockUs,
      offsetUs,
      uncertaintyUs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ClockOffsetSample decode(Object result) {
    result as List<Object?>;
    return ClockOffsetSample(
      cameraClockUs: result[0]! as int,
      motionClockUs: result[1]! as int,
      offsetUs: result[2]! as int,
      uncertaintyUs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ClockOffsetSample || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cameraClockUs, other.cameraClockUs) && _deepEquals(motionClockUs, other.motionClockUs) && _deepEquals(offsetUs, other.offsetUs) && _deepEquals(uncertaintyUs, other.uncertaintyUs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ClockOffsetSample(cameraClockUs: $cameraClockUs, motionClockUs: $motionClockUs, offsetUs: $offsetUs, uncertaintyUs: $uncertaintyUs)';
  }
}

/// The result of opening a camera: everything later stages are only valid for.
class CameraOpenResult {
  CameraOpenResult({
    required this.captureSize,
    required this.previewSize,
    required this.sensorOrientationDegrees,
    required this.previewRotationDegrees,
    required this.previewHandlesRotation,
    required this.clock,
    required this.bracketMode,
    required this.maxBracketCount,
    required this.captureAspectIsFourThree,
    this.androidFacts,
    this.iosFacts,
    this.warning,
  });

  PlatformSize captureSize;

  PlatformSize previewSize;

  /// Sensor mounting rotation, needed to reconcile the portrait lock with the
  /// sensor's native orientation.
  int sensorOrientationDegrees;

  /// Clockwise degrees the **preview texture still needs** to stand upright on a
  /// portrait screen: `0`, `90`, `180` or `270`.
  ///
  /// The platform states this rather than Dart inferring it, and the difference is
  /// not academic — it is the bug that took four attempts to find. Every input to
  /// the inference is something the device says about itself: the sensor mounting,
  /// the reported preview size, and — the one that actually decided it — whether
  /// the render path already applied the rotation. On Android that last answer
  /// comes from `SurfaceProducer.handlesCropAndRotation()`, is `true` on the legacy
  /// texture path and `false` on the API 29+ `ImageReader` backend, and cannot be
  /// derived from anything visible to Dart. A derivation that got the first two
  /// right still turned a correct preview sideways.
  ///
  /// So: `0` when the buffer arrives upright, and the mounting angle when it does
  /// not. Dart applies exactly this and nothing else.
  int previewRotationDegrees;

  /// Whether the render path handled the crop and rotation metadata itself.
  ///
  /// Reported alongside [previewRotationDegrees] rather than folded into it because
  /// the two answer different questions — "how far do I turn it" and "why" — and the
  /// second is what makes a bug report from an unfamiliar device actionable. It
  /// lands in `bundle.json`, so a capture carries the reason with it.
  bool previewHandlesRotation;

  ClockSyncInfo clock;

  /// The bracket path this device will actually take, decided at open time so
  /// the caller can adjust the plan rather than discover it at frame 1.
  PlatformBracketMode bracketMode;

  int maxBracketCount;

  /// False means a crop factor entered the intrinsics and §2.1's preference
  /// could not be honoured. Worth surfacing: it changes the derivation.
  bool captureAspectIsFourThree;

  AndroidIntrinsicFacts? androidFacts;

  IosIntrinsicFacts? iosFacts;

  /// Any compromise made while opening. Never silently degrade (arch §8).
  String? warning;

  List<Object?> _toList() {
    return <Object?>[
      captureSize,
      previewSize,
      sensorOrientationDegrees,
      previewRotationDegrees,
      previewHandlesRotation,
      clock,
      bracketMode,
      maxBracketCount,
      captureAspectIsFourThree,
      androidFacts,
      iosFacts,
      warning,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraOpenResult decode(Object result) {
    result as List<Object?>;
    return CameraOpenResult(
      captureSize: result[0]! as PlatformSize,
      previewSize: result[1]! as PlatformSize,
      sensorOrientationDegrees: result[2]! as int,
      previewRotationDegrees: result[3]! as int,
      previewHandlesRotation: result[4]! as bool,
      clock: result[5]! as ClockSyncInfo,
      bracketMode: result[6]! as PlatformBracketMode,
      maxBracketCount: result[7]! as int,
      captureAspectIsFourThree: result[8]! as bool,
      androidFacts: result[9] as AndroidIntrinsicFacts?,
      iosFacts: result[10] as IosIntrinsicFacts?,
      warning: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraOpenResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(captureSize, other.captureSize) && _deepEquals(previewSize, other.previewSize) && _deepEquals(sensorOrientationDegrees, other.sensorOrientationDegrees) && _deepEquals(previewRotationDegrees, other.previewRotationDegrees) && _deepEquals(previewHandlesRotation, other.previewHandlesRotation) && _deepEquals(clock, other.clock) && _deepEquals(bracketMode, other.bracketMode) && _deepEquals(maxBracketCount, other.maxBracketCount) && _deepEquals(captureAspectIsFourThree, other.captureAspectIsFourThree) && _deepEquals(androidFacts, other.androidFacts) && _deepEquals(iosFacts, other.iosFacts) && _deepEquals(warning, other.warning);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraOpenResult(captureSize: $captureSize, previewSize: $previewSize, sensorOrientationDegrees: $sensorOrientationDegrees, previewRotationDegrees: $previewRotationDegrees, previewHandlesRotation: $previewHandlesRotation, clock: $clock, bracketMode: $bracketMode, maxBracketCount: $maxBracketCount, captureAspectIsFourThree: $captureAspectIsFourThree, androidFacts: $androidFacts, iosFacts: $iosFacts, warning: $warning)';
  }
}

/// Who made this device and what it is called.
///
/// Phase 11 §2 writes these into the output's EXIF `Make`/`Model`. That is not
/// bookkeeping: a construction record is looked at months later by somebody
/// deciding whether to trust it, and "which tablet took this" is the first
/// question when one station's panoramas are visibly worse than the rest of the
/// walk. It is also the only way a field failure can be tied to a device model
/// without asking the person who captured it to remember.
class DeviceIdentity {
  DeviceIdentity({
    required this.make,
    required this.model,
    required this.osVersion,
  });

  /// `Build.MANUFACTURER` on Android; `Apple` on iOS.
  String make;

  /// `Build.MODEL` on Android; the hardware identifier (`iPad14,3`) on iOS.
  ///
  /// The identifier rather than the marketing name, because the marketing name
  /// needs a lookup table that goes stale with every release, and the
  /// identifier is what a capability question is actually answered against.
  String model;

  /// OS release string, for the bundle's diagnostic record.
  String osVersion;

  List<Object?> _toList() {
    return <Object?>[
      make,
      model,
      osVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceIdentity decode(Object result) {
    result as List<Object?>;
    return DeviceIdentity(
      make: result[0]! as String,
      model: result[1]! as String,
      osVersion: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceIdentity || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(make, other.make) && _deepEquals(model, other.model) && _deepEquals(osVersion, other.osVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceIdentity(make: $make, model: $model, osVersion: $osVersion)';
  }
}

/// What the metering pre-sweep settled on, and how firmly.
class MeteringResult {
  MeteringResult({
    required this.exposureTimeNs,
    required this.iso,
    required this.colorTemperatureK,
    required this.focusDistanceDiopters,
    required this.lockQuality,
    required this.sampleCount,
    required this.chosenEv,
    required this.meanEv,
    required this.percentile65Ev,
    required this.aeConverged,
    required this.pinnedProcessingModes,
    this.note,
  });

  /// The exposure locked for the whole session.
  int exposureTimeNs;

  int iso;

  int colorTemperatureK;

  /// Locked focus, in diopters. §2.3: near the hyperfocal distance — locking
  /// to infinity softens near objects, locking to macro ruins everything else.
  double focusDistanceDiopters;

  PlatformLockQuality lockQuality;

  /// How many frames the sweep observed. A sweep that saw three frames did not
  /// see the sphere, and its percentile means nothing.
  int sampleCount;

  /// The EV actually locked, relative to the sweep's own median frame.
  double chosenEv;

  /// Reported alongside [percentile65Ev] so the §2.3 decision is *visible* in
  /// the data rather than only in the code: interiors are mid-tone with a few
  /// bright windows, and the mean is dragged bright by the windows and crushes
  /// the interior.
  double meanEv;

  double percentile65Ev;

  bool aeConverged;

  /// Whether `NOISE_REDUCTION` / `EDGE` / `TONEMAP` / `COLOR_CORRECTION` were
  /// pinned to fixed modes (§2.3 step 5). Easy to miss, and leaving any of
  /// them adaptive reintroduces exactly the per-frame photometric
  /// inconsistency the AE lock exists to remove.
  bool pinnedProcessingModes;

  String? note;

  List<Object?> _toList() {
    return <Object?>[
      exposureTimeNs,
      iso,
      colorTemperatureK,
      focusDistanceDiopters,
      lockQuality,
      sampleCount,
      chosenEv,
      meanEv,
      percentile65Ev,
      aeConverged,
      pinnedProcessingModes,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static MeteringResult decode(Object result) {
    result as List<Object?>;
    return MeteringResult(
      exposureTimeNs: result[0]! as int,
      iso: result[1]! as int,
      colorTemperatureK: result[2]! as int,
      focusDistanceDiopters: result[3]! as double,
      lockQuality: result[4]! as PlatformLockQuality,
      sampleCount: result[5]! as int,
      chosenEv: result[6]! as double,
      meanEv: result[7]! as double,
      percentile65Ev: result[8]! as double,
      aeConverged: result[9]! as bool,
      pinnedProcessingModes: result[10]! as bool,
      note: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MeteringResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(exposureTimeNs, other.exposureTimeNs) && _deepEquals(iso, other.iso) && _deepEquals(colorTemperatureK, other.colorTemperatureK) && _deepEquals(focusDistanceDiopters, other.focusDistanceDiopters) && _deepEquals(lockQuality, other.lockQuality) && _deepEquals(sampleCount, other.sampleCount) && _deepEquals(chosenEv, other.chosenEv) && _deepEquals(meanEv, other.meanEv) && _deepEquals(percentile65Ev, other.percentile65Ev) && _deepEquals(aeConverged, other.aeConverged) && _deepEquals(pinnedProcessingModes, other.pinnedProcessingModes) && _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MeteringResult(exposureTimeNs: $exposureTimeNs, iso: $iso, colorTemperatureK: $colorTemperatureK, focusDistanceDiopters: $focusDistanceDiopters, lockQuality: $lockQuality, sampleCount: $sampleCount, chosenEv: $chosenEv, meanEv: $meanEv, percentile65Ev: $percentile65Ev, aeConverged: $aeConverged, pinnedProcessingModes: $pinnedProcessingModes, note: $note)';
  }
}

/// One frame returned by a bracketed capture.
class PlatformFrame {
  PlatformFrame({
    required this.filePath,
    required this.evBias,
    required this.timestampUs,
    required this.byteCount,
    this.exposureTimeNs,
    this.iso,
    this.achievedEvBias,
    this.meanR,
    this.meanG,
    this.meanB,
    this.note,
  });

  String filePath;

  /// The bias in stops this frame was *requested* at.
  double evBias;

  /// Shutter instant, already converted to the single monotonic microsecond
  /// base the pose stream shares (§2.5, §3.5).
  int timestampUs;

  int byteCount;

  /// What the sensor actually did, as opposed to what was asked for. When a
  /// bracket comes back with two identical frames — the failure R3 warns about
  /// on devices without real bracketing — this is the only evidence of it.
  int? exposureTimeNs;

  int? iso;

  /// Computed from the *actual* exposure and ISO, so the "EV separation within
  /// 0.3 EV of requested" check is against reality rather than intent.
  double? achievedEvBias;

  /// Centre-crop channel means, present only when
  /// [CaptureFormatRequest.computeFrameStatistics] is set. The grey-card
  /// AE/AWB lock measurement (§6).
  double? meanR;

  double? meanG;

  double? meanB;

  String? note;

  List<Object?> _toList() {
    return <Object?>[
      filePath,
      evBias,
      timestampUs,
      byteCount,
      exposureTimeNs,
      iso,
      achievedEvBias,
      meanR,
      meanG,
      meanB,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformFrame decode(Object result) {
    result as List<Object?>;
    return PlatformFrame(
      filePath: result[0]! as String,
      evBias: result[1]! as double,
      timestampUs: result[2]! as int,
      byteCount: result[3]! as int,
      exposureTimeNs: result[4] as int?,
      iso: result[5] as int?,
      achievedEvBias: result[6] as double?,
      meanR: result[7] as double?,
      meanG: result[8] as double?,
      meanB: result[9] as double?,
      note: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformFrame || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(filePath, other.filePath) && _deepEquals(evBias, other.evBias) && _deepEquals(timestampUs, other.timestampUs) && _deepEquals(byteCount, other.byteCount) && _deepEquals(exposureTimeNs, other.exposureTimeNs) && _deepEquals(iso, other.iso) && _deepEquals(achievedEvBias, other.achievedEvBias) && _deepEquals(meanR, other.meanR) && _deepEquals(meanG, other.meanG) && _deepEquals(meanB, other.meanB) && _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformFrame(filePath: $filePath, evBias: $evBias, timestampUs: $timestampUs, byteCount: $byteCount, exposureTimeNs: $exposureTimeNs, iso: $iso, achievedEvBias: $achievedEvBias, meanR: $meanR, meanG: $meanG, meanB: $meanB, note: $note)';
  }
}

/// One bracket's worth of frames plus the timing the 600 ms budget is judged
/// against.
class CaptureResponse {
  CaptureResponse({
    required this.frames,
    required this.burstWallClockMs,
    required this.shutterToShutterMs,
    required this.mode,
    required this.clampedExposure,
    required this.clampedIso,
    required this.deferredEncodeMs,
    this.note,
  });

  List<PlatformFrame> frames;

  /// Trigger → last frame's **pixels in hand**, not `onCaptureCompleted`.
  /// Metadata routinely completes well before pixels are delivered, and pixels
  /// are what Phase 05 needs; timing the metadata would give a flattering,
  /// useless number (Spike C).
  double burstWallClockMs;

  /// From sensor timestamps: what the sensor sustains, separated from what
  /// processing then costs. That distinction is what the JPEG-vs-YUV decision
  /// turns on (R3 §9).
  List<double> shutterToShutterMs;

  PlatformBracketMode mode;

  /// Clamping is reported, never silent: a silently clamped bracket looks like
  /// a passing capture while delivering less dynamic range than assumed.
  bool clampedExposure;

  bool clampedIso;

  /// What the YUV path moved *off* the hot path — not what it removed.
  double deferredEncodeMs;

  String? note;

  List<Object?> _toList() {
    return <Object?>[
      frames,
      burstWallClockMs,
      shutterToShutterMs,
      mode,
      clampedExposure,
      clampedIso,
      deferredEncodeMs,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureResponse decode(Object result) {
    result as List<Object?>;
    return CaptureResponse(
      frames: (result[0]! as List<Object?>).cast<PlatformFrame>(),
      burstWallClockMs: result[1]! as double,
      shutterToShutterMs: (result[2]! as List<Object?>).cast<double>(),
      mode: result[3]! as PlatformBracketMode,
      clampedExposure: result[4]! as bool,
      clampedIso: result[5]! as bool,
      deferredEncodeMs: result[6]! as double,
      note: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(frames, other.frames) && _deepEquals(burstWallClockMs, other.burstWallClockMs) && _deepEquals(shutterToShutterMs, other.shutterToShutterMs) && _deepEquals(mode, other.mode) && _deepEquals(clampedExposure, other.clampedExposure) && _deepEquals(clampedIso, other.clampedIso) && _deepEquals(deferredEncodeMs, other.deferredEncodeMs) && _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureResponse(frames: $frames, burstWallClockMs: $burstWallClockMs, shutterToShutterMs: $shutterToShutterMs, mode: $mode, clampedExposure: $clampedExposure, clampedIso: $clampedIso, deferredEncodeMs: $deferredEncodeMs, note: $note)';
  }
}

/// What this device can actually do, and — when it cannot — why.
///
/// Exists so a gyro-less tablet is refused at the feature entry point with a
/// sentence a site manager can act on, rather than producing a panorama built
/// on accelerometer tilt alone (Phase 07 §6 pitfall 3, Phase 12 §1).
class PoseCapabilities {
  PoseCapabilities({
    required this.hasGyroscope,
    required this.hasAccelerometer,
    required this.hasFusedRotation,
    required this.hasGravity,
    required this.usesMagnetometer,
    required this.frame,
    required this.minDelayUs,
    required this.detail,
    this.unsupportedReason,
  });

  /// The one hard requirement. Without it there is no attitude source that
  /// tracks a pan, and the pipeline cannot work at all.
  bool hasGyroscope;

  /// Needed for the gravity lock that makes pitch and roll drift-free.
  bool hasAccelerometer;

  /// Whether the fused, magnetometer-free attitude sensor is present —
  /// `TYPE_GAME_ROTATION_VECTOR` on Android, `isDeviceMotionAvailable` on iOS.
  bool hasFusedRotation;

  /// Whether a fused gravity vector is available (`TYPE_GRAVITY` /
  /// `CMDeviceMotion.gravity`). Its absence is recoverable — raw accelerometer
  /// would do — but it is reported because [PlatformPoseSample.upX] is what the
  /// levelling step of Math §7 ultimately rests on.
  bool hasGravity;

  /// **Must be false.** Reported rather than assumed so that a build which
  /// accidentally selected `TYPE_ROTATION_VECTOR` or `.xTrueNorthZVertical`
  /// shows up as a recorded fact in the bundle instead of as an unexplained
  /// heading error on a site with steel in the walls.
  bool usesMagnetometer;

  /// The frame [PlatformPoseSample]'s quaternion is expressed against.
  PlatformPoseFrame frame;

  /// The fastest the attitude source will run, in µs between samples.
  /// `Sensor.getMinDelay()` on Android; 0 where the platform does not say.
  int minDelayUs;

  /// Plain-language description of what was found, for the bundle and the
  /// report.
  String detail;

  /// Non-null exactly when this device cannot be supported, phrased as
  /// something the user can act on.
  String? unsupportedReason;

  List<Object?> _toList() {
    return <Object?>[
      hasGyroscope,
      hasAccelerometer,
      hasFusedRotation,
      hasGravity,
      usesMagnetometer,
      frame,
      minDelayUs,
      detail,
      unsupportedReason,
    ];
  }

  Object encode() {
    return _toList();  }

  static PoseCapabilities decode(Object result) {
    result as List<Object?>;
    return PoseCapabilities(
      hasGyroscope: result[0]! as bool,
      hasAccelerometer: result[1]! as bool,
      hasFusedRotation: result[2]! as bool,
      hasGravity: result[3]! as bool,
      usesMagnetometer: result[4]! as bool,
      frame: result[5]! as PlatformPoseFrame,
      minDelayUs: result[6]! as int,
      detail: result[7]! as String,
      unsupportedReason: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PoseCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasGyroscope, other.hasGyroscope) && _deepEquals(hasAccelerometer, other.hasAccelerometer) && _deepEquals(hasFusedRotation, other.hasFusedRotation) && _deepEquals(hasGravity, other.hasGravity) && _deepEquals(usesMagnetometer, other.usesMagnetometer) && _deepEquals(frame, other.frame) && _deepEquals(minDelayUs, other.minDelayUs) && _deepEquals(detail, other.detail) && _deepEquals(unsupportedReason, other.unsupportedReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PoseCapabilities(hasGyroscope: $hasGyroscope, hasAccelerometer: $hasAccelerometer, hasFusedRotation: $hasFusedRotation, hasGravity: $hasGravity, usesMagnetometer: $usesMagnetometer, frame: $frame, minDelayUs: $minDelayUs, detail: $detail, unsupportedReason: $unsupportedReason)';
  }
}

/// How pose timestamps were reconciled with the clock Phase 06 puts shutter
/// timestamps on.
class PoseClockInfo {
  PoseClockInfo({
    required this.base,
    required this.offsetUs,
    required this.uncertaintyUs,
    required this.note,
  });

  PlatformPoseClockBase base;

  /// Added to a raw sample timestamp to land on the shared motion clock.
  /// Exactly `0` for [PlatformPoseClockBase.androidElapsedRealtime] and
  /// [PlatformPoseClockBase.iosSystemUptime], where the two *are* one clock.
  int offsetUs;

  /// Bound on the offset estimate. Zero when nothing needed estimating.
  int uncertaintyUs;

  String note;

  List<Object?> _toList() {
    return <Object?>[
      base,
      offsetUs,
      uncertaintyUs,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static PoseClockInfo decode(Object result) {
    result as List<Object?>;
    return PoseClockInfo(
      base: result[0]! as PlatformPoseClockBase,
      offsetUs: result[1]! as int,
      uncertaintyUs: result[2]! as int,
      note: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PoseClockInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(base, other.base) && _deepEquals(offsetUs, other.offsetUs) && _deepEquals(uncertaintyUs, other.uncertaintyUs) && _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PoseClockInfo(base: $base, offsetUs: $offsetUs, uncertaintyUs: $uncertaintyUs, note: $note)';
  }
}

/// What starting the stream settled.
class PoseStreamInfo {
  PoseStreamInfo({
    required this.frame,
    required this.clock,
    required this.samplingPeriodUs,
    required this.minDelayUs,
    required this.note,
  });

  PlatformPoseFrame frame;

  PoseClockInfo clock;

  /// The period actually requested of the platform (§4 asks for 10 000 µs).
  int samplingPeriodUs;

  /// The floor the platform imposes on it; 0 when unreported.
  int minDelayUs;

  String note;

  List<Object?> _toList() {
    return <Object?>[
      frame,
      clock,
      samplingPeriodUs,
      minDelayUs,
      note,
    ];
  }

  Object encode() {
    return _toList();  }

  static PoseStreamInfo decode(Object result) {
    result as List<Object?>;
    return PoseStreamInfo(
      frame: result[0]! as PlatformPoseFrame,
      clock: result[1]! as PoseClockInfo,
      samplingPeriodUs: result[2]! as int,
      minDelayUs: result[3]! as int,
      note: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PoseStreamInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(frame, other.frame) && _deepEquals(clock, other.clock) && _deepEquals(samplingPeriodUs, other.samplingPeriodUs) && _deepEquals(minDelayUs, other.minDelayUs) && _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PoseStreamInfo(frame: $frame, clock: $clock, samplingPeriodUs: $samplingPeriodUs, minDelayUs: $minDelayUs, note: $note)';
  }
}

/// One attitude sample, exactly as the platform reported it.
///
/// **No frame conversion happens on the native side.** This is the same
/// decision the intrinsics chain makes for the same reason, one step further:
/// Phase 07 §2 says the world→world conversion "must be proven by the §5 test,
/// not by derivation", and a conversion that lives in Kotlin and Swift can only
/// ever be tested on the two devices in the room. In Dart it is one function,
/// pinned by unit tests over every branch, and the device test then confirms
/// the platform docs rather than the arithmetic.
class PlatformPoseSample {
  PlatformPoseSample({
    required this.qx,
    required this.qy,
    required this.qz,
    required this.qw,
    required this.upX,
    required this.upY,
    required this.upZ,
    required this.angularSpeedRadPerSec,
    required this.timestampUs,
    required this.sequence,
    required this.accuracy,
  });

  /// Device→reference rotation, in the frame named by [PoseStreamInfo.frame].
  double qx;

  double qy;

  double qz;

  double qw;

  /// A **unit** vector in the *device* frame pointing **away from the earth**.
  ///
  /// Normalised natively rather than passed raw because the two platforms
  /// disagree on both magnitude and sign: Android `TYPE_GRAVITY` reads
  /// `(0, 0, +9.81)` with the device flat on its back, iOS
  /// `CMDeviceMotion.gravity` reads `(0, 0, −1)` in the same pose. Reconciling
  /// that is a one-line, per-platform fact about what a sensor reads in a known
  /// physical pose — which is precisely the kind of thing the native side is
  /// here to report — and it leaves Dart with one convention instead of two.
  ///
  /// Dart does **not** take it on trust: `PlatformAhrsPoseSource` checks that
  /// this vector, rotated into the world frame, actually comes out pointing up,
  /// and refuses to start if it does not (Phase 07 §2's reflection hazard, in
  /// its detectable half).
  double upX;

  double upY;

  double upZ;

  /// `|ω|` from the gyroscope, rad/s. A magnitude rather than a vector because
  /// it is frame-invariant, which keeps one more sign convention out of the
  /// wire format — and the steadiness gate only ever wants the magnitude.
  double angularSpeedRadPerSec;

  /// Sample instant on the shared motion clock, already converted by
  /// [PoseClockInfo.offsetUs].
  int timestampUs;

  /// Monotonic counter from the start of the stream, so a gap in delivery is
  /// distinguishable from a gap in sampling.
  int sequence;

  /// Android `SensorEvent.accuracy` (`SENSOR_STATUS_*`); `-1` on iOS, which
  /// publishes no equivalent.
  int accuracy;

  List<Object?> _toList() {
    return <Object?>[
      qx,
      qy,
      qz,
      qw,
      upX,
      upY,
      upZ,
      angularSpeedRadPerSec,
      timestampUs,
      sequence,
      accuracy,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformPoseSample decode(Object result) {
    result as List<Object?>;
    return PlatformPoseSample(
      qx: result[0]! as double,
      qy: result[1]! as double,
      qz: result[2]! as double,
      qw: result[3]! as double,
      upX: result[4]! as double,
      upY: result[5]! as double,
      upZ: result[6]! as double,
      angularSpeedRadPerSec: result[7]! as double,
      timestampUs: result[8]! as int,
      sequence: result[9]! as int,
      accuracy: result[10]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPoseSample || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(qx, other.qx) && _deepEquals(qy, other.qy) && _deepEquals(qz, other.qz) && _deepEquals(qw, other.qw) && _deepEquals(upX, other.upX) && _deepEquals(upY, other.upY) && _deepEquals(upZ, other.upZ) && _deepEquals(angularSpeedRadPerSec, other.angularSpeedRadPerSec) && _deepEquals(timestampUs, other.timestampUs) && _deepEquals(sequence, other.sequence) && _deepEquals(accuracy, other.accuracy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPoseSample(qx: $qx, qy: $qy, qz: $qz, qw: $qw, upX: $upX, upY: $upY, upZ: $upZ, angularSpeedRadPerSec: $angularSpeedRadPerSec, timestampUs: $timestampUs, sequence: $sequence, accuracy: $accuracy)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformCameraFacing) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformThermalState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformLockQuality) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PlatformTimestampBase) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PlatformCaptureFormat) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is PlatformBracketMode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is PlatformHardwareLevel) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is PlatformPoseFrame) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is PlatformPoseClockBase) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is PlatformSize) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformRect) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is CameraDescriptor) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureFormatRequest) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidIntrinsicFacts) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is IosIntrinsicFacts) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is ClockSyncInfo) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is ClockOffsetSample) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is CameraOpenResult) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceIdentity) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is MeteringResult) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformFrame) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureResponse) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is PoseCapabilities) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is PoseClockInfo) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is PoseStreamInfo) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformPoseSample) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformCameraFacing.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformThermalState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformLockQuality.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformTimestampBase.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformCaptureFormat.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBracketMode.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformHardwareLevel.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformPoseFrame.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformPoseClockBase.values[value];
      case 138:
        return PlatformSize.decode(readValue(buffer)!);
      case 139:
        return PlatformRect.decode(readValue(buffer)!);
      case 140:
        return CameraDescriptor.decode(readValue(buffer)!);
      case 141:
        return CaptureFormatRequest.decode(readValue(buffer)!);
      case 142:
        return AndroidIntrinsicFacts.decode(readValue(buffer)!);
      case 143:
        return IosIntrinsicFacts.decode(readValue(buffer)!);
      case 144:
        return ClockSyncInfo.decode(readValue(buffer)!);
      case 145:
        return ClockOffsetSample.decode(readValue(buffer)!);
      case 146:
        return CameraOpenResult.decode(readValue(buffer)!);
      case 147:
        return DeviceIdentity.decode(readValue(buffer)!);
      case 148:
        return MeteringResult.decode(readValue(buffer)!);
      case 149:
        return PlatformFrame.decode(readValue(buffer)!);
      case 150:
        return CaptureResponse.decode(readValue(buffer)!);
      case 151:
        return PoseCapabilities.decode(readValue(buffer)!);
      case 152:
        return PoseClockInfo.decode(readValue(buffer)!);
      case 153:
        return PoseStreamInfo.decode(readValue(buffer)!);
      case 154:
        return PlatformPoseSample.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SphereCameraHostApi {
  /// Constructor for [SphereCameraHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SphereCameraHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Enumerates the physical cameras and their capabilities.
  Future<List<CameraDescriptor>> listCameras() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.listCameras$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CameraDescriptor>();
  }

  /// Opens [cameraId] and configures the capture and preview streams.
  Future<CameraOpenResult> open(String cameraId, CaptureFormatRequest format) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.open$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cameraId, format]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CameraOpenResult;
  }

  /// Attaches the preview and returns the Flutter texture id. Preview is
  /// delivered through the platform texture APIs; bytes are never streamed
  /// over the channel (§4).
  Future<int> attachPreview() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.attachPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Releases the preview texture without closing the camera.
  Future<void> detachPreview() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.detachPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Runs the metering pre-sweep for [durationSeconds], then hard-locks AE,
  /// AWB and AF for the rest of the session.
  Future<MeteringResult> meterAndLock(double durationSeconds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.meterAndLock$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[durationSeconds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MeteringResult;
  }

  /// Releases the lock.
  Future<void> unlock() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.unlock$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Fires one bracket at [evBiases], writing frames into [outputDirectory]
  /// with names beginning [namePrefix].
  Future<CaptureResponse> captureBracket(List<double> evBiases, String outputDirectory, String namePrefix) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.captureBracket$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[evBiases, outputDirectory, namePrefix]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CaptureResponse;
  }

  /// Current thermal state (§5).
  Future<PlatformThermalState> thermalState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.thermalState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformThermalState;
  }

  /// Re-measures the camera↔motion clock offset. Called repeatedly by the §6
  /// stability test; cheap enough to call in a loop.
  Future<ClockOffsetSample> sampleClockOffset() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.sampleClockOffset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ClockOffsetSample;
  }

  /// Make, model and OS version, for the output's EXIF (Phase 11 §2).
  ///
  /// On the camera API rather than the pose one because it is asked once, at
  /// open time, alongside every other fact about the hardware that took the
  /// frames.
  Future<DeviceIdentity> deviceIdentity() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.deviceIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DeviceIdentity;
  }

  /// The largest texture edge this GPU will accept, in pixels (Phase 11 §3.1).
  ///
  /// The viewer needs this before it uploads a panorama, and it is the one
  /// number that decides whether the sphere renders or comes up **black**.
  /// Many mid-range tablet GPUs cap at 4096, and an 8192-wide upload against
  /// such a cap does not raise an error — it silently produces nothing, which
  /// looks exactly like a stitcher that emitted an empty image.
  ///
  /// Returns 0 when the platform cannot say, which the caller must read as
  /// "assume the conservative floor" rather than "no limit".
  Future<int> maxTextureSize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.maxTextureSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Total physical RAM in MB, for the memory-tier probe (arch §6.5).
  Future<int> totalPhysicalMemoryMb() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.totalPhysicalMemoryMb$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// How much more memory *this process* may allocate, in MB, or `-1` where
  /// the platform will not say.
  ///
  /// Not the tier decision — that is [totalPhysicalMemoryMb], and it is total
  /// rather than available on purpose (Phase 10 §4): available fluctuates, and
  /// a tier that moves with it would make output resolution differ between two
  /// runs on the same device, which makes a bug report useless.
  ///
  /// This is the pre-flight check instead. iOS answers it with
  /// `os_proc_available_memory()`, and it matters there specifically because
  /// iOS kills a process on memory pressure with no recoverable signal — no
  /// `bad_alloc` to catch, no chance to drop a tier. So the only defence is to
  /// ask before starting, and to start one tier lower if the answer is smaller
  /// than the tier needs. Android returns `-1`: it has no per-process
  /// equivalent, and a real `OutOfMemoryError` there *is* catchable, so the
  /// retry path covers it.
  Future<int> availableProcessMemoryMb() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.availableProcessMemoryMb$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Battery charge as a whole percentage, or `-1` where the platform will not
  /// say.
  ///
  /// Phase 12 §3 asks for the drain **per station** to be measured and
  /// published, because a site walk is up to thirty of them and a tablet that
  /// cannot finish one is a feature nobody can use. It is a percentage rather
  /// than a mAh figure on purpose: percentage is what both platforms report
  /// without a vendor API, and the number that matters is "how many stations
  /// does this tablet have left", which is a percentage divided by a
  /// percentage.
  ///
  /// It is coarse — most devices report in steps of 1% and some in steps of 5%
  /// — so one station's drain is at or below the quantisation. The device matrix
  /// therefore measures across a *run* of stations and divides, which is also
  /// the number a site lead actually wants.
  Future<int> batteryPercent() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.batteryPercent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Closes the camera and releases every resource.
  Future<void> close() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SphereCameraHostApi.close$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class SphereCameraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// A preview frame is ready, stamped on the shared monotonic base. Phase 07
  /// pairs this with the pose stream.
  void onFrameAvailable(int timestampUs);

  /// Something went wrong outside a pending call — a disconnect, a HAL error,
  /// a dropped burst.
  void onError(String code, String message);

  /// Thermal state changed (§5). At `serious` the UI warns and suggests
  /// stitching later; at `critical` a stitch is refused and told why.
  void onThermalStateChanged(PlatformThermalState state);

  /// The session was interrupted or resumed — a phone call, another app, or
  /// split view on iPad, where a second app taking the camera is common
  /// (§7 pitfall 3).
  void onSessionInterrupted(bool interrupted, String reason);

  static void setUp(SphereCameraFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sphere_view.SphereCameraFlutterApi.onFrameAvailable$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_timestampUs = args[0]! as int;
          try {
            api.onFrameAvailable(arg_timestampUs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sphere_view.SphereCameraFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_code = args[0]! as String;
          final String arg_message = args[1]! as String;
          try {
            api.onError(arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sphere_view.SphereCameraFlutterApi.onThermalStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformThermalState arg_state = args[0]! as PlatformThermalState;
          try {
            api.onThermalStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sphere_view.SphereCameraFlutterApi.onSessionInterrupted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_interrupted = args[0]! as bool;
          final String arg_reason = args[1]! as String;
          try {
            api.onSessionInterrupted(arg_interrupted, arg_reason);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

/// The AHRS half (Phase 07).
///
/// Deliberately a second API rather than more methods on
/// [SphereCameraHostApi]: the pose stream outlives any one camera session — §6
/// pitfall 5 says never reset the buffer between targets — and it must keep
/// running while the camera is closed and reopened. Two APIs make that
/// independence structural instead of a convention someone has to remember.
class SpherePoseHostApi {
  /// Constructor for [SpherePoseHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SpherePoseHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// What this device's motion hardware can do. Cheap, and callable before
  /// anything is started, because Phase 12 §1 refuses an unsupported device at
  /// the *feature entry point* — before the camera opens, before the user has
  /// walked to the first station.
  Future<PoseCapabilities> poseCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SpherePoseHostApi.poseCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PoseCapabilities;
  }

  /// Starts the attitude stream at [samplingPeriodUs] (§4 asks for 10 000 µs,
  /// i.e. 100 Hz).
  ///
  /// Throws when the device is unsupported, so the refusal cannot be missed by
  /// a caller that forgot to check [poseCapabilities] first.
  Future<PoseStreamInfo> startPose(int samplingPeriodUs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SpherePoseHostApi.startPose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[samplingPeriodUs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PoseStreamInfo;
  }

  /// Stops the stream and releases the sensors.
  Future<void> stopPose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sphere_view.SpherePoseHostApi.stopPose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class SpherePoseFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// One attitude sample, at the requested rate.
  ///
  /// One message per sample rather than a batch: the guidance reticle of Phase
  /// 09 is driven from the newest pose, and batching 100 Hz into 10 Hz packets
  /// would add up to 100 ms of visible lag to the aim gate for no benefit the
  /// interpolator needs — `PoseBuffer.at()` always looks *backwards* to a
  /// shutter that has already happened, so delivery latency costs it nothing
  /// and staleness costs the UI directly.
  void onPoseSample(PlatformPoseSample sample);

  /// The stream failed after starting — the sensor was unregistered by the OS,
  /// or motion updates stopped. Never silent (architecture §8).
  void onPoseError(String code, String message);

  static void setUp(SpherePoseFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sphere_view.SpherePoseFlutterApi.onPoseSample$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformPoseSample arg_sample = args[0]! as PlatformPoseSample;
          try {
            api.onPoseSample(arg_sample);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sphere_view.SpherePoseFlutterApi.onPoseError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_code = args[0]! as String;
          final String arg_message = args[1]! as String;
          try {
            api.onPoseError(arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
